version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3005 -b '0.0.0.0'"
    volumes:
      - .:/rails-lock
      - gem_data:/usr/local/bundle
    ports:
      - "3005:3005"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  gem_data:
